-- 1. Tabla Clientes
CREATE TABLE Clientes (
    ClienteID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PrimerNombre VARCHAR2(50) NOT NULL,
    SegundoNombre VARCHAR2(50),
    ApellidoPaterno VARCHAR2(50) NOT NULL,
    ApellidoMaterno VARCHAR2(50),
    FechaNacimiento DATE,
    Telefono VARCHAR2(20),
    Correo VARCHAR2(100),
    Genero CHAR(1), 
    FechaRegistro DATE DEFAULT SYSDATE
);

-- 2. Tabla Membresias
CREATE TABLE Membresias (
    MembresiaID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nombre VARCHAR2(50),
    Precio NUMBER(10,2),
    DuracionDias NUMBER,
    AccesoPiscina NUMBER(1),
    AccesoClases NUMBER(1)
);

-- 3. Tabla ClientesMembresias
CREATE TABLE ClientesMembresias (
    ClienteMembresiaID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ClienteID NUMBER,
    MembresiaID NUMBER,
    FechaInicio DATE,
    FechaFin DATE,
    Estado VARCHAR2(20),
    MetodoPago VARCHAR2(50), 
    FOREIGN KEY (ClienteID) REFERENCES Clientes(ClienteID),
    FOREIGN KEY (MembresiaID) REFERENCES Membresias(MembresiaID)
);

-- 4. Tabla Entrenadores
CREATE TABLE Entrenadores (
    EntrenadorID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nombre VARCHAR2(50),
    Apellido VARCHAR2(50),
    Especialidad VARCHAR2(50),
    Telefono VARCHAR2(20),
    Correo VARCHAR2(100)
);

-- 5. Tabla Clases
CREATE TABLE Clases (
    ClaseID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nombre VARCHAR2(50),
    EntrenadorID NUMBER,
    DiaSemana VARCHAR2(20),
    HoraInicio DATE, -- Puedes usar DATE para guardar solo hora
    DuracionMinutos NUMBER,
    CapacidadMaxima NUMBER,
    FOREIGN KEY (EntrenadorID) REFERENCES Entrenadores(EntrenadorID)
);

-- 6. Tabla AsistenciaClases
CREATE TABLE AsistenciaClases (
    AsistenciaID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ClienteID NUMBER,
    ClaseID NUMBER,
    FechaAsistencia DATE,
    Asistio NUMBER(1) DEFAULT 1, 
    FOREIGN KEY (ClienteID) REFERENCES Clientes(ClienteID),
    FOREIGN KEY (ClaseID) REFERENCES Clases(ClaseID)
);