-- Script para crear la tabla de usuarios del sistema
CREATE TABLE usuarios_nuevos (
    usuario_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) NOT NULL UNIQUE,
    password VARCHAR2(100) NOT NULL,
    rol VARCHAR2(20) NOT NULL,
    activo NUMBER(1) DEFAULT 1
);

-- Insertar un usuario de prueba (recepcionista)
INSERT INTO usuarios_nuevos (username, password, rol) 
VALUES ('admin', 'admin123', 'recepcionista');

COMMIT;
